@startuml
skinparam shadowing false

title Schéma Global


class Global{
    + Symptomes
    + Maladies
    + Médicaments
    + Médicaments_soignants
    + Source
    + (Score)
}

class MedDra_all_se {
    + code_MedDra : CID1xxxxxxxx
    + CUI
    + nom_symptome
}

class Stitch{
    + code_MedDra 
    + CUI : CIDs
    + code_ATC
}

class ATC{
    + code_ATC (niv E)
    + nom_medicament (E et F)
}

class HPO_Annotations {
    + source_db
    + id_maladie 
    + nom_maladie
    + sign_id : 0010527
}

class HPO_OBO{
    + id : 0010527
    + name : nom_symptome
    + synonym : synonyme_symptome
}

class OMIM_Onto {
    + PreferredLabel : nom_courant_symptome
    + Synonyms : synonyme_symptome
    + CUI
}

class OMIM{
    + NO : id_maladie
    + TI : nom_maladie
    + CS : nom_symptome 
}

class MedDra {
    + CUI
    + nom_symptome
}

class DrugBank {
    + name : nom_medicament
    + indication : Maladies
    + toxicity : Effets secondaires
    + synonym : synonyme_medicament
}


class MedDra_all_indications {
    + Code_MedDra
    + CUI
    + Symptomes-Maladies
}

class MedDra_freq{
    + Code_MedDra
    + CUI
    + Pourcentage (Score)
    + Symptomes  
}

Global::Symptomes -- HPO_OBO::nom_symptome
Global::Symptomes -- MedDra::nom_symptome
Global::Symptomes -- OMIM::nom_symptome
Global::Maladies -- DrugBank::indication
Global::Médicaments -- DrugBank::toxicity
Global::Symptomes -- MedDra_all_indications::Symptomes
Global::Symptomes -- MedDra_all_se::nom_symptome


HPO_OBO::id -- HPO_Annotations::sign_id
HPO_Annotations::nom_maladie -- Global::Maladies


MedDra::CUI--OMIM_Onto::CUI
OMIM_Onto::Synonyms-- Global::Symptomes

OMIM::nom_maladie--Global::Maladies
OMIM::id_maladie--HPO_Annotations::id_maladie


ATC::nom_medicament -- Global::Médicaments
MedDra_all_se::code_MedDra -- Stitch::code_MedDra
Stitch::code_ATC-- ATC::code_ATC 
MedDra_freq::Pourcentage -- Global::Score
MedDra_all_se::CUI -- MedDra_freq::CUI
MedDra_all_indications::Symptomes -- Global::Maladies


DrugBank::name -- Global::Médicaments_soignants
@enduml