@startuml
skinparam shadowing false

title Schéma Global


class Global{
    + Symptomes
    + Maladies
    + Médicaments
    + Source
    + (Score)
}

class MedDRA_all_se {
    + code_MedDRA : CID1xxxxxxxx
    + (CUI)
    + nom_symptome
}

class Stitch{
    + code_MedDRA
    + (CUI : CIDs)
    + code_ATC
}

class ATC{
    + code_ATC (niv E)
    + nom_medicament (E et F)
}

class HPO_Annotations {
    + source_db
    + id_maladie 
    + nom_maladie
    + sign_id : 0010527
}

class HPO_OBO{
    + id : 0010527
    + name : nom_symptome
    + synonym : synonyme_symptome
}

class OMIM_Onto {
    + PreferredLabel : nom_courant_symptome
    + Synonyms : synonyme_symptome
    + CUI
}

class OMIM{
    + NO : id_maladie
    + TI : nom_maladie
    + CS : nom_symptome 
}

class MedDRA {
    + CUI
    + nom_symptome
}

class DrugBank {
    + nom_medicament
    + indication : Maladies
    + toxicity : Effets secondaires
    + Synonyme_medicament
    + ATC
}


class MedDra_all_indications {
    + Code_MedDRA
    + CUI
    + Symptomes
}

class MeDra_freq{
    + Code_MedDRA
    + CUI
    + Pourcentage (Score)
    + Symptomes  
}

Global::Symptomes --> HPO_OBO::nom_symptome
Global::Symptomes --> MedDRA::nom_symptome
Global::Symptomes --> OMIM::nom_symptome
Global::Maladies --> DrugBank::indication
Global::Symptomes --> DrugBank::toxicity
Global::Symptomes --> MedDra_all_indications::Symptomes
Global::Symptomes --> MedDRA_all_se::nom_symptome


HPO_OBO::id --> HPO_Annotations::sign_id
HPO_Annotations::nom_maladie --> Global::Maladies

DrugBank::nom_medicament --> Global::Médicaments

MedDRA::CUI-->OMIM_Onto::CUI
OMIM_Onto::Synonyms--> Global::Symptomes

OMIM::nom_maladie-->Global::Maladies
OMIM::id_maladie-->HPO_Annotations::id_maladie


ATC::nom_medicament --> Global::Médicaments
MedDRA_all_se::code_MedDRA --> Stitch::code_MedDRA
Stitch::code_ATC--> ATC::code_ATC 
MeDra_freq::Pourcentage --> Global::Score
MedDra_all_indications::CUI --> MeDra_freq::CUI
